# Makefile for Asyn heli support
#
# Created by moffit on Fri Jun  3 21:33:20 2022
# Based on the Asyn app template

TOP = .
include $(TOP)/configure/CONFIG

DIRS := configure
DIRS += $(wildcard *[Ss]up)
DIRS += $(wildcard *[Aa]pp)
DIRS += $(wildcard ioc[Bb]oot)

include $(TOP)/configure/RULES_TOP
